// Code generated by jasonlabz/gentol. DO NOT EDIT.
// Code generated by jasonlabz/gentol. DO NOT EDIT.
// Code generated by jasonlabz/gentol. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
)

var gormDB *gorm.DB

func SetGormDB(db *gorm.DB) {
	if db == nil {
		panic("db connection is nil")
	}
	gormDB = db
	return
}

func DB() *gorm.DB {
	if gormDB == nil {
		panic("db connection is nil")
	}
	return gormDB
}

func RunTransaction(ctx context.Context, f func(ctx context.Context) error) error {
	// 使用 Transaction 方法并绑定上下文
	return DB().WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		transCtx := context.WithValue(ctx, "transactionDB", tx)
		// 在事务中创建用户
		if err := f(transCtx); err != nil {
			return err // 返回错误，事务会回滚
		}
		return nil // 返回 nil，事务会提交
	})
}
