// Code generated by MockGen. DO NOT EDIT.
// Source: F:/baidu/aiib-go/generate-example-project/server/controller/health_check/register.go
//
// Generated by this command:
//
//	mockgen -source F:/baidu/aiib-go/generate-example-project/server/controller/health_check/register.go -destination F:/baidu/aiib-go/generate-example-project/server/mocks/server/controller/health_check/mock_register.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	huma "github.com/danielgtaylor/huma/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthCheckController is a mock of HealthCheckController interface.
type MockHealthCheckController struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckControllerMockRecorder
	isgomock struct{}
}

// MockHealthCheckControllerMockRecorder is the mock recorder for MockHealthCheckController.
type MockHealthCheckControllerMockRecorder struct {
	mock *MockHealthCheckController
}

// NewMockHealthCheckController creates a new mock instance.
func NewMockHealthCheckController(ctrl *gomock.Controller) *MockHealthCheckController {
	mock := &MockHealthCheckController{ctrl: ctrl}
	mock.recorder = &MockHealthCheckControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthCheckController) EXPECT() *MockHealthCheckControllerMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockHealthCheckController) Register(api huma.API) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", api)
}

// Register indicates an expected call of Register.
func (mr *MockHealthCheckControllerMockRecorder) Register(api any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockHealthCheckController)(nil).Register), api)
}
