#!/usr/bin/env bash

set -euo pipefail

usage() {
	printf 'Usage: %s [-p path1,path2,...] [-o output-root] [-s strip-prefix]\n' "${0##*/}" >&2
}

is_within_project_root() {
	local path="$1"

	[[ "$path" == "$project_root" || "$path" == "$project_root"/* ]]
}

normalize_path() {
	local path="$1"

	if [[ "$path" =~ ^[A-Za-z]:[\\/].* ]]; then
		path="$(cygpath --unix "$path")"
	fi
	if [[ "$path" != /* ]]; then
		path="$project_root/$path"
	fi
	realpath -m "$path"
}

paths='.'
mock_root='server/mocks'
strip=''

while getopts 'hp:o:s:' opt; do
	case "$opt" in
	h) usage; exit 0 ;;
	p) paths=$OPTARG ;;
	o) mock_root=$OPTARG ;;
	s) strip=$OPTARG ;;
	*) usage; exit 2 ;;
	esac
done
shift $((OPTIND - 1))
if (($# > 0)); then
	usage
	exit 2
fi

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
mock_root="$(normalize_path "$mock_root")"
if ! is_within_project_root "$mock_root"; then
	echo "error: output path must be within project root: $mock_root" >&2
	exit 2
fi

IFS=',' read -r -a requested_paths <<< "$paths"
source_roots=()
for requested_path in "${requested_paths[@]}"; do
	if [[ -z "$requested_path" ]]; then
		echo 'skip absent source directory: ' >&2
		continue
	fi

	source_root="$(normalize_path "$requested_path")"
	if ! is_within_project_root "$source_root"; then
		echo "error: source path must be within project root: $source_root" >&2
		exit 2
	fi
	if [[ ! -d "$source_root" ]]; then
		echo "skip absent source directory: $requested_path" >&2
		continue
	fi
	source_roots+=("$source_root")
done

if ((${#source_roots[@]} == 0)); then
	echo 'error: no valid source directories' >&2
	exit 2
fi

command -v mockgen >/dev/null 2>&1 || {
	echo 'error: mockgen not found in PATH' >&2
	echo 'install: go install go.uber.org/mock/mockgen@latest' >&2
	exit 1
}

mkdir -p "$mock_root"
while IFS= read -r -d '' candidate; do
	if grep -q '^// Code generated by MockGen\. DO NOT EDIT\.' "$candidate"; then
		rm -- "$candidate"
	fi
done < <(find "$mock_root" -type f -name 'mock_*.go' -print0)

scanner_args=(-root "$project_root" -exclude "$mock_root")
for source_root in "${source_roots[@]}"; do
	scanner_args+=(-path "$source_root")
done

while IFS= read -r source_relative_path; do
	[[ -z "$source_relative_path" ]] && continue

	source_path="$project_root/$source_relative_path"
	mapped_source_path="$source_relative_path"
	if [[ -n "$strip" && "$source_relative_path" == "$strip/"* ]]; then
		mapped_source_path="${source_relative_path#"$strip/"}"
	fi

	destination_directory="$mock_root/$(dirname "$mapped_source_path")"
	if [[ "$source_relative_path" == internal/* ]]; then
		internal_prefix=''
		internal_suffix="${source_relative_path#internal/}"
	elif [[ "$source_relative_path" == */internal/* ]]; then
		# The shortest suffix selects the deepest internal boundary for nested paths.
		internal_prefix="${source_relative_path%/internal/*}"
		internal_suffix="${source_relative_path#"$internal_prefix/internal/"}"
	else
		internal_prefix=''
		internal_suffix=''
	fi

	if [[ -n "$internal_suffix" ]]; then
		internal_parent="$project_root"
		if [[ -n "$internal_prefix" ]]; then
			internal_parent="$internal_parent/$internal_prefix"
		fi
		if [[ "$destination_directory" != "$internal_parent" && "$destination_directory" != "$internal_parent"/* ]]; then
			internal_directory="$(dirname "$internal_suffix")"
			destination_directory="$internal_parent/.mocks/internal"
			if [[ "$internal_directory" != '.' ]]; then
				destination_directory="$destination_directory/$internal_directory"
			fi
			redirected=true
		else
			redirected=false
		fi
	else
		redirected=false
	fi

	source_filename="$(basename "$source_relative_path" .go)"
	target="$destination_directory/mock_${source_filename}.go"
	if [[ "$redirected" == true ]]; then
		printf 'redirect internal mock: %s -> %s\n' "$source_path" "$target"
	fi
	mkdir -p "$destination_directory"
	mockgen -source="$source_path" -destination="$target" -package=mocks
done < <(go run ./script/internal/mockscan "${scanner_args[@]}")
