#!/usr/bin/env bash

set -euo pipefail

usage() {
	printf 'Usage: %s [-p path1,path2,...] [-o output-root] [-s strip-prefix]\n' "${0##*/}" >&2
}

script_dir="${BASH_SOURCE[0]%/*}"
if [[ "$script_dir" == "${BASH_SOURCE[0]}" ]]; then
	script_dir='.'
fi
project_root="$(cd "$script_dir/.." && pwd -P)"

is_within_project_root() {
	local path="$1"

	[[ "$path" == "$project_root" || "$path" == "$project_root"/* ]]
}

# Resolve paths that may not exist yet without relying on GNU realpath.
normalize_path() {
	local path="$1"
	local suffix=''
	local parent

	if [[ "$path" =~ ^[A-Za-z]:[\\\\/].* ]]; then
		if ! command -v cygpath >/dev/null 2>&1; then
			echo "error: Windows path requires cygpath: $path" >&2
			exit 2
		fi
		path="$(cygpath --unix "$path")"
	fi
	if [[ "$path" != /* ]]; then
		path="$project_root/$path"
	fi
	while [[ ! -e "$path" && "$path" != '/' ]]; do
		parent="${path%/*}"
		if [[ "$parent" == "$path" || -z "$parent" ]]; then
			parent='/'
		fi
		suffix="/${path##*/}${suffix}"
		path="$parent"
	done
	path="$(cd "$path" && pwd -P)"
	printf '%s%s\n' "$path" "$suffix"
}

paths='.'
mock_root='server/mocks'
strip=''

while getopts 'hp:o:s:' opt; do
	case "$opt" in
		h) usage; exit 0 ;;
		p) paths="$OPTARG" ;;
		o) mock_root="$OPTARG" ;;
		s) strip="$OPTARG" ;;
		*) usage; exit 2 ;;
	esac
done
shift $((OPTIND - 1))
if (($# > 0)); then
	usage
	exit 2
fi

# Check this before optional filesystem tools so an empty PATH gives a useful error.
if ! command -v mockgen >/dev/null 2>&1; then
	echo 'error: mockgen not found in PATH' >&2
	echo 'install: go install go.uber.org/mock/mockgen@latest' >&2
	exit 1
fi

mock_root="$(normalize_path "$mock_root")"
if ! is_within_project_root "$mock_root"; then
	echo "error: output path must be within project root: $mock_root" >&2
	exit 2
fi

strip="${strip#./}"
strip="${strip%/}"
if [[ "$strip" == '.' ]]; then
	strip=''
fi

IFS=',' read -r -a requested_paths <<< "$paths"
source_roots=()
for requested_path in "${requested_paths[@]}"; do
	if [[ -z "$requested_path" ]]; then
		echo 'skip absent source directory:' >&2
		continue
	fi

	source_root="$(normalize_path "$requested_path")"
	if ! is_within_project_root "$source_root"; then
		echo "error: source path must be within project root: $source_root" >&2
		exit 2
	fi
	if [[ ! -d "$source_root" ]]; then
		echo "skip absent source directory: $requested_path" >&2
		continue
	fi
	source_roots+=("$source_root")
done

if ((${#source_roots[@]} == 0)); then
	echo 'error: no valid source directories' >&2
	exit 2
fi

mkdir -p "$mock_root"
while IFS= read -r -d '' candidate; do
	if grep -q '^// Code generated by MockGen\. DO NOT EDIT\.' "$candidate"; then
		rm -- "$candidate"
	fi
done < <(find "$mock_root" -type f -name 'mock_*.go' -print0)

has_exported_interface() {
	local source_path="$1"

	LC_ALL=C grep -Eq '^[[:space:]]*type[[:space:]]+[A-Z][A-Za-z0-9_]*[[:space:]]+interface([[:space:]]|\{)' "$source_path"
}

source_files=()
for source_root in "${source_roots[@]}"; do
	while IFS= read -r -d '' source_path; do
		case "$source_path" in
			*_test.go|*.gen.go|*_generated.go|*/mock_*.go)
				continue
				;;
		esac
		if grep -q '^// Code generated by' "$source_path" || ! has_exported_interface "$source_path"; then
			continue
		fi
		source_files+=("$source_path")
	done < <(
		find "$source_root" \
			-path "$mock_root" -prune -o \
			-path '*/.git' -prune -o \
			-path '*/vendor' -prune -o \
			-path '*/.mocks' -prune -o \
			-type f -name '*.go' -print0
	)
done

while IFS= read -r source_path; do
	case "$source_path" in
		'') continue ;;
	esac

	source_relative_path="${source_path#"$project_root/"}"
	mapped_source_path="$source_relative_path"
	if [[ -n "$strip" && "$mapped_source_path" == "$strip/"* ]]; then
		mapped_source_path="${mapped_source_path#"$strip/"}"
	fi

	if [[ "$mapped_source_path" == */* ]]; then
		source_directory="${mapped_source_path%/*}"
	else
		source_directory='.'
	fi
	source_filename="${source_relative_path##*/}"
	source_filename="${source_filename%.go}"
	destination_directory="$mock_root/$source_directory"
	target="$destination_directory/mock_$source_filename.go"

	mkdir -p "$destination_directory"
	mockgen -source="$source_path" -destination="$target" -package=mocks
done < <(printf '%s\n' "${source_files[@]}" | LC_ALL=C sort -u)
