package script

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

type mockgenFixtureProject struct {
	root          string
	bash          string
	binPath       string
	invocationLog string
}

// TestGoMockgen verifies the shell generator contract in an isolated Go project.
func TestGoMockgen(t *testing.T) {
	fixture := newMockgenFixtureProject(t)

	t.Run("uses-default-output-and-skips-generated-source", func(t *testing.T) {
		runFixtureMockgen(t, fixture, "-p", "server/api")
		assertFileExists(t, filepath.Join(fixture.root, "server", "mocks", "server", "api", "mock_contract.go"))
		assertFileDoesNotExist(t, filepath.Join(fixture.root, "server", "mocks", "server", "api", "mock_ignored.gen.go"))
		assertFileDoesNotExist(t, filepath.Join(fixture.root, "server", "mocks", "server", "api", "mock_constants.go"))
		assertFileDoesNotExist(t, filepath.Join(fixture.root, ".mocks", "internal", "dao", "interfaces", "mock_contract.go"))
		assertFakeMockgenInvoked(t, fixture)
	})

	t.Run("strips-internal-prefix", func(t *testing.T) {
		runFixtureMockgen(t, fixture, "-p", "internal/dao/interfaces", "-o", "internal/mocks", "-s", "internal")
		assertFileExists(t, filepath.Join(fixture.root, "internal", "mocks", "dao", "interfaces", "mock_contract.go"))
		assertFakeMockgenInvoked(t, fixture)
	})

	t.Run("does-not-scan-output-root", func(t *testing.T) {
		writeFixtureFile(t, fixture.root, "server/mocks/poison.go", "package mocks\n\ntype MustNotGenerate interface { Stop() }\n")
		runFixtureMockgen(t, fixture, "-p", "server")
		assertFileDoesNotExist(t, filepath.Join(fixture.root, "server", "mocks", "server", "mocks", "mock_poison.go"))
		assertFakeMockgenInvoked(t, fixture)
	})

	t.Run("removes-only-marker-bearing-stale-mocks", func(t *testing.T) {
		staleMock := filepath.Join(fixture.root, "server", "mocks", "stale", "mock_stale.go")
		readme := filepath.Join(fixture.root, "server", "mocks", "README.md")
		manualMock := filepath.Join(fixture.root, "server", "mocks", "mock_manual.go")
		writeFixtureFile(t, fixture.root, "server/mocks/stale/mock_stale.go", "// Code generated by MockGen. DO NOT EDIT.\n\npackage mocks\n")
		writeFixtureFile(t, fixture.root, "server/mocks/README.md", "kept\n")
		writeFixtureFile(t, fixture.root, "server/mocks/mock_manual.go", "package mocks\n")

		runFixtureMockgen(t, fixture, "-p", "server/api")
		assertFileDoesNotExist(t, staleMock)
		assertFileExists(t, readme)
		assertFileExists(t, manualMock)
		assertFakeMockgenInvoked(t, fixture)
	})

	t.Run("mirrors-nested-internal-output", func(t *testing.T) {
		runFixtureMockgen(t, fixture, "-p", "cmd/tool/internal/sample")
		assertFileExists(t, filepath.Join(fixture.root, "server", "mocks", "cmd", "tool", "internal", "sample", "mock_contract.go"))
		assertFakeMockgenInvoked(t, fixture)
	})

	t.Run("reports-missing-mockgen-on-empty-path", func(t *testing.T) {
		output, err := runFixtureMockgenCommand(fixture, "", nil)
		if err == nil {
			t.Fatal("go-mockgen.sh succeeded without mockgen on PATH")
		}
		if !strings.Contains(string(output), "mockgen not found in PATH") {
			t.Fatalf("missing mockgen error\n%s", output)
		}
	})
}

func newMockgenFixtureProject(t *testing.T) mockgenFixtureProject {
	// newMockgenFixtureProject copies live generator inputs into a temporary module and seeds the contract fixtures.
	t.Helper()

	root := t.TempDir()
	writeFixtureFile(t, root, "go.mod", "module mockgenfixture\n\ngo 1.25.0\n")
	copyFixtureFile(t, root, "script/go-mockgen.sh")
	writeFixtureFile(t, root, "server/api/contract.go", "package api\n\ntype Contract interface { Run() error }\n")
	writeFixtureFile(t, root, "server/api/ignored_test.go", "package api\n\ntype TestOnly interface { Stop() }\n")
	writeFixtureFile(t, root, "server/api/ignored.gen.go", "package api\n\ntype Generated interface { Reset() }\n")
	writeFixtureFile(t, root, "server/api/constants.go", "package api\n\nconst Name = \"example\"\n")
	writeFixtureFile(t, root, "internal/dao/interfaces/contract.go", "package interfaces\n\ntype Repository interface { Find() error }\n")
	writeFixtureFile(t, root, "cmd/tool/internal/sample/contract.go", "package sample\n\ntype Contract interface { Run() error }\n")

	binPath := filepath.Join(root, "bin")
	invocationLog := filepath.Join(root, "mockgen-invocations.log")
	buildFixtureMockgen(t, root, binPath)
	return mockgenFixtureProject{root: root, bash: gitBashPath(t), binPath: binPath, invocationLog: invocationLog}
}

func copyFixtureFile(t *testing.T, fixtureRoot, relativePath string) {
	t.Helper()

	content, err := os.ReadFile(filepath.Join(projectRoot(t), relativePath))
	if err != nil {
		t.Fatalf("read live fixture file %q: %v", relativePath, err)
	}
	writeFixtureFile(t, fixtureRoot, relativePath, string(content))
}

func writeFixtureFile(t *testing.T, root, relativePath, content string) {
	t.Helper()

	path := filepath.Join(root, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("create fixture directory for %q: %v", relativePath, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write fixture file %q: %v", relativePath, err)
	}
}

func buildFixtureMockgen(t *testing.T, root, binPath string) {
	t.Helper()

	writeFixtureFile(t, root, "tools/mockgen/main.go", "package main\n\nimport (\n\t\"flag\"\n\t\"log\"\n\t\"os\"\n\t\"path/filepath\"\n)\n\nfunc main() {\n\tsource := flag.String(\"source\", \"\", \"source file\")\n\tdestination := flag.String(\"destination\", \"\", \"destination file\")\n\tpackageName := flag.String(\"package\", \"\", \"destination package\")\n\tflag.Parse()\n\tif *source == \"\" || *destination == \"\" || *packageName == \"\" {\n\t\tlog.Fatal(\"-source, -destination, and -package are required\")\n\t}\n\tinvocationLog := os.Getenv(\"MOCKGEN_INVOCATION_LOG\")\n\tif invocationLog == \"\" {\n\t\tlog.Fatal(\"MOCKGEN_INVOCATION_LOG is required\")\n\t}\n\tif err := os.WriteFile(invocationLog, []byte(*source+\"\\n\"), 0o600); err != nil {\n\t\tlog.Fatal(err)\n\t}\n\tif err := os.MkdirAll(filepath.Dir(*destination), 0o755); err != nil {\n\t\tlog.Fatal(err)\n\t}\n\tcontent := \"// Code generated by MockGen. DO NOT EDIT.\\n\\npackage \" + *packageName + \"\\n\"\n\tif err := os.WriteFile(*destination, []byte(content), 0o600); err != nil {\n\t\tlog.Fatal(err)\n\t}\n}\n")

	if err := os.MkdirAll(binPath, 0o755); err != nil {
		t.Fatalf("create fake mockgen directory: %v", err)
	}
	command := exec.Command("go", "build", "-o", filepath.Join(binPath, "mockgen"), "./tools/mockgen")
	command.Dir = root
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("build fake mockgen: %v\n%s", err, output)
	}
}

func resetFakeMockgenInvocationLog(t *testing.T, fixture mockgenFixtureProject) {
	t.Helper()

	if err := os.Remove(fixture.invocationLog); err != nil && !os.IsNotExist(err) {
		t.Fatalf("reset fake mockgen invocation log: %v", err)
	}
}

func runFixtureMockgen(t *testing.T, fixture mockgenFixtureProject, arguments ...string) {
	t.Helper()

	resetFakeMockgenInvocationLog(t, fixture)
	output, err := runFixtureMockgenCommand(fixture, fixture.binPath, arguments)
	if err != nil {
		t.Fatalf("run go-mockgen.sh: %v\n%s", err, output)
	}
}

func runFixtureMockgenCommand(fixture mockgenFixtureProject, path string, arguments []string) ([]byte, error) {
	command := exec.Command(fixture.bash, append([]string{"script/go-mockgen.sh"}, arguments...)...)
	command.Dir = fixture.root
	command.Env = append(withPath(os.Environ(), path), "MOCKGEN_INVOCATION_LOG="+fixture.invocationLog)
	return command.CombinedOutput()
}

func withPath(environment []string, path string) []string {
	const prefix = "PATH="
	environment = append([]string(nil), environment...)
	for index, variable := range environment {
		if strings.HasPrefix(strings.ToUpper(variable), prefix) {
			if path == "" {
				environment[index] = prefix
			} else {
				environment[index] = prefix + path + string(os.PathListSeparator) + variable[len(prefix):]
			}
			return environment
		}
	}
	return append(environment, prefix+path)
}

func projectRoot(t *testing.T) string {
	t.Helper()

	directory, err := os.Getwd()
	if err != nil {
		t.Fatalf("get working directory: %v", err)
	}

	return filepath.Dir(directory)
}

func gitBashPath(t *testing.T) string {
	t.Helper()

	if runtime.GOOS != "windows" {
		path, err := exec.LookPath("bash")
		if err != nil {
			t.Fatalf("find bash: %v", err)
		}
		return path
	}

	for _, path := range []string{
		filepath.Join(os.Getenv("ProgramFiles"), "Git", "bin", "bash.exe"),
		filepath.Join(os.Getenv("ProgramFiles(x86)"), "Git", "bin", "bash.exe"),
	} {
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}

	t.Fatal("Git Bash is required to run script/go-mockgen.sh on Windows")
	return ""
}

func assertFakeMockgenInvoked(t *testing.T, fixture mockgenFixtureProject) {
	t.Helper()

	content, err := os.ReadFile(fixture.invocationLog)
	if err != nil {
		t.Fatalf("read fake mockgen invocation log: %v", err)
	}
	if !strings.Contains(string(content), "contract.go") {
		t.Fatalf("fake mockgen invocation log does not record a contract source: %q", content)
	}
}

func assertFileExists(t *testing.T, path string) {
	t.Helper()

	if _, err := os.Stat(path); err != nil {
		t.Fatalf("expected generated file %q: %v", path, err)
	}
}

func assertFileDoesNotExist(t *testing.T, path string) {
	t.Helper()

	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("unexpected generated file %q: %v", path, err)
	}
}
