// Code generated by jasonlabz/gentol. DO NOT EDIT.
// Code generated by jasonlabz/gentol. DO NOT EDIT.
// Code generated by jasonlabz/gentol. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"

	"github.com/jasonlabz/null"
	"github.com/satori/go.uuid"
)

var (
	_ = time.Second
	_ = sql.LevelDefault
	_ = null.Bool{}
	_ = uuid.UUID{}
)

type UserField string

// User struct is mapping to the user table
type User struct {
	UserID int64 `gorm:"primaryKey;autoIncrement;column:user_id;not null;type:bigint(20)" json:"user_id"` // Comment: 用户ID

	Nickname string `gorm:"column:nickname;not null;type:varchar(255)" json:"nickname"` // Comment: 用户名

	Avatar string `gorm:"column:avatar;not null;type:varchar(255)" json:"avatar"` // Comment: 头像

	Password string `gorm:"column:password;not null;type:varchar(255)" json:"password"` // Comment: 用户密码 des/md5加密值

	Phone string `gorm:"unique;column:phone;not null;type:varchar(255);uniqueIndex:phone" json:"phone"` // Comment: 手机号 aes加密

	Gender int32 `gorm:"column:gender;not null;type:int(11);default:9" json:"gender"` // Comment: 性别 0|男、1|女、9|未知

	Status int32 `gorm:"column:status;not null;type:int(11);default:0" json:"status"` // Comment: 状态 0|正常、1|注销、2|冻结

	RegisterIP string `gorm:"column:register_ip;not null;type:varchar(255)" json:"register_ip"` // Comment: 注册IP

	RegisterTime time.Time `gorm:"column:register_time;not null;type:timestamp;default:current_timestamp()" json:"register_time"` // Comment: 注册时间

	LastLoginIP string `gorm:"column:last_login_ip;not null;type:varchar(255)" json:"last_login_ip"` // Comment: 最后登录IP

	LastLoginTime time.Time `gorm:"column:last_login_time;not null;type:timestamp;default:current_timestamp()" json:"last_login_time"` // Comment: 最后登录时间

	CreateTime time.Time `gorm:"column:create_time;not null;type:timestamp;default:current_timestamp()" json:"create_time"` // Comment: no comment

	UpdateTime time.Time `gorm:"column:update_time;not null;type:timestamp;default:current_timestamp()" json:"update_time"` // Comment: no comment
}

func (u *User) TableName() string {
	return "user"
}

type UserTableColumn struct {
	UserID        UserField
	Nickname      UserField
	Avatar        UserField
	Password      UserField
	Phone         UserField
	Gender        UserField
	Status        UserField
	RegisterIP    UserField
	RegisterTime  UserField
	LastLoginIP   UserField
	LastLoginTime UserField
	CreateTime    UserField
	UpdateTime    UserField
}

type UserCondition struct {
	Condition
}

func (u *UserCondition) ColumnInfo() UserTableColumn {
	return UserTableColumn{
		UserID:        "user_id",
		Nickname:      "nickname",
		Avatar:        "avatar",
		Password:      "password",
		Phone:         "phone",
		Gender:        "gender",
		Status:        "status",
		RegisterIP:    "register_ip",
		RegisterTime:  "register_time",
		LastLoginIP:   "last_login_ip",
		LastLoginTime: "last_login_time",
		CreateTime:    "create_time",
		UpdateTime:    "update_time",
	}
}

func (u *UserCondition) UserIDIsNull() *UserCondition {
	return u.Where("user_id is null")
}

func (u *UserCondition) UserIDIsNotNull() *UserCondition {
	return u.Where("user_id is not null")
}

func (u *UserCondition) UserIDEqualTo(value int64) *UserCondition {
	return u.Where("user_id = ?", value)
}

func (u *UserCondition) UserIDNotEqualTo(value int64) *UserCondition {
	return u.Where("user_id <> ?", value)
}

func (u *UserCondition) UserIDGreaterThan(value int64) *UserCondition {
	return u.Where("user_id > ?", value)
}

func (u *UserCondition) UserIDGreaterThanOrEqualTo(value int64) *UserCondition {
	return u.Where("user_id >= ?", value)
}

func (u *UserCondition) UserIDLessThan(value int64) *UserCondition {
	return u.Where("user_id < ?", value)
}

func (u *UserCondition) UserIDLessThanOrEqualTo(value int64) *UserCondition {
	return u.Where("user_id <= ?", value)
}

func (u *UserCondition) UserIDBetween(startValue, endValue int64) *UserCondition {
	return u.Where("user_id between ? and ?", startValue, endValue)
}

func (u *UserCondition) UserIDNotBetween(startValue, endValue int64) *UserCondition {
	return u.Where("user_id not between ? and ?", startValue, endValue)
}

func (u *UserCondition) UserIDIn(inValues []int64) *UserCondition {
	return u.Where("user_id in (?)", inValues)
}

func (u *UserCondition) UserIDNotIn(inValues []int64) *UserCondition {
	return u.Where("user_id not in (?)", inValues)
}

func (u *UserCondition) NicknamePrefixLike(value string) *UserCondition {
	return u.Where("nickname like ?", value+"%")
}

func (u *UserCondition) NicknameIsLike(value string) *UserCondition {
	return u.Where("nickname like ?", "%"+value+"%")
}

func (u *UserCondition) NicknameIsNull() *UserCondition {
	return u.Where("nickname is null")
}

func (u *UserCondition) NicknameIsNotNull() *UserCondition {
	return u.Where("nickname is not null")
}

func (u *UserCondition) NicknameEqualTo(value string) *UserCondition {
	return u.Where("nickname = ?", value)
}

func (u *UserCondition) NicknameNotEqualTo(value string) *UserCondition {
	return u.Where("nickname <> ?", value)
}

func (u *UserCondition) NicknameGreaterThan(value string) *UserCondition {
	return u.Where("nickname > ?", value)
}

func (u *UserCondition) NicknameGreaterThanOrEqualTo(value string) *UserCondition {
	return u.Where("nickname >= ?", value)
}

func (u *UserCondition) NicknameLessThan(value string) *UserCondition {
	return u.Where("nickname < ?", value)
}

func (u *UserCondition) NicknameLessThanOrEqualTo(value string) *UserCondition {
	return u.Where("nickname <= ?", value)
}

func (u *UserCondition) NicknameBetween(startValue, endValue string) *UserCondition {
	return u.Where("nickname between ? and ?", startValue, endValue)
}

func (u *UserCondition) NicknameNotBetween(startValue, endValue string) *UserCondition {
	return u.Where("nickname not between ? and ?", startValue, endValue)
}

func (u *UserCondition) NicknameIn(inValues []string) *UserCondition {
	return u.Where("nickname in (?)", inValues)
}

func (u *UserCondition) NicknameNotIn(inValues []string) *UserCondition {
	return u.Where("nickname not in (?)", inValues)
}

func (u *UserCondition) AvatarPrefixLike(value string) *UserCondition {
	return u.Where("avatar like ?", value+"%")
}

func (u *UserCondition) AvatarIsLike(value string) *UserCondition {
	return u.Where("avatar like ?", "%"+value+"%")
}

func (u *UserCondition) AvatarIsNull() *UserCondition {
	return u.Where("avatar is null")
}

func (u *UserCondition) AvatarIsNotNull() *UserCondition {
	return u.Where("avatar is not null")
}

func (u *UserCondition) AvatarEqualTo(value string) *UserCondition {
	return u.Where("avatar = ?", value)
}

func (u *UserCondition) AvatarNotEqualTo(value string) *UserCondition {
	return u.Where("avatar <> ?", value)
}

func (u *UserCondition) AvatarGreaterThan(value string) *UserCondition {
	return u.Where("avatar > ?", value)
}

func (u *UserCondition) AvatarGreaterThanOrEqualTo(value string) *UserCondition {
	return u.Where("avatar >= ?", value)
}

func (u *UserCondition) AvatarLessThan(value string) *UserCondition {
	return u.Where("avatar < ?", value)
}

func (u *UserCondition) AvatarLessThanOrEqualTo(value string) *UserCondition {
	return u.Where("avatar <= ?", value)
}

func (u *UserCondition) AvatarBetween(startValue, endValue string) *UserCondition {
	return u.Where("avatar between ? and ?", startValue, endValue)
}

func (u *UserCondition) AvatarNotBetween(startValue, endValue string) *UserCondition {
	return u.Where("avatar not between ? and ?", startValue, endValue)
}

func (u *UserCondition) AvatarIn(inValues []string) *UserCondition {
	return u.Where("avatar in (?)", inValues)
}

func (u *UserCondition) AvatarNotIn(inValues []string) *UserCondition {
	return u.Where("avatar not in (?)", inValues)
}

func (u *UserCondition) PasswordPrefixLike(value string) *UserCondition {
	return u.Where("password like ?", value+"%")
}

func (u *UserCondition) PasswordIsLike(value string) *UserCondition {
	return u.Where("password like ?", "%"+value+"%")
}

func (u *UserCondition) PasswordIsNull() *UserCondition {
	return u.Where("password is null")
}

func (u *UserCondition) PasswordIsNotNull() *UserCondition {
	return u.Where("password is not null")
}

func (u *UserCondition) PasswordEqualTo(value string) *UserCondition {
	return u.Where("password = ?", value)
}

func (u *UserCondition) PasswordNotEqualTo(value string) *UserCondition {
	return u.Where("password <> ?", value)
}

func (u *UserCondition) PasswordGreaterThan(value string) *UserCondition {
	return u.Where("password > ?", value)
}

func (u *UserCondition) PasswordGreaterThanOrEqualTo(value string) *UserCondition {
	return u.Where("password >= ?", value)
}

func (u *UserCondition) PasswordLessThan(value string) *UserCondition {
	return u.Where("password < ?", value)
}

func (u *UserCondition) PasswordLessThanOrEqualTo(value string) *UserCondition {
	return u.Where("password <= ?", value)
}

func (u *UserCondition) PasswordBetween(startValue, endValue string) *UserCondition {
	return u.Where("password between ? and ?", startValue, endValue)
}

func (u *UserCondition) PasswordNotBetween(startValue, endValue string) *UserCondition {
	return u.Where("password not between ? and ?", startValue, endValue)
}

func (u *UserCondition) PasswordIn(inValues []string) *UserCondition {
	return u.Where("password in (?)", inValues)
}

func (u *UserCondition) PasswordNotIn(inValues []string) *UserCondition {
	return u.Where("password not in (?)", inValues)
}

func (u *UserCondition) PhonePrefixLike(value string) *UserCondition {
	return u.Where("phone like ?", value+"%")
}

func (u *UserCondition) PhoneIsLike(value string) *UserCondition {
	return u.Where("phone like ?", "%"+value+"%")
}

func (u *UserCondition) PhoneIsNull() *UserCondition {
	return u.Where("phone is null")
}

func (u *UserCondition) PhoneIsNotNull() *UserCondition {
	return u.Where("phone is not null")
}

func (u *UserCondition) PhoneEqualTo(value string) *UserCondition {
	return u.Where("phone = ?", value)
}

func (u *UserCondition) PhoneNotEqualTo(value string) *UserCondition {
	return u.Where("phone <> ?", value)
}

func (u *UserCondition) PhoneGreaterThan(value string) *UserCondition {
	return u.Where("phone > ?", value)
}

func (u *UserCondition) PhoneGreaterThanOrEqualTo(value string) *UserCondition {
	return u.Where("phone >= ?", value)
}

func (u *UserCondition) PhoneLessThan(value string) *UserCondition {
	return u.Where("phone < ?", value)
}

func (u *UserCondition) PhoneLessThanOrEqualTo(value string) *UserCondition {
	return u.Where("phone <= ?", value)
}

func (u *UserCondition) PhoneBetween(startValue, endValue string) *UserCondition {
	return u.Where("phone between ? and ?", startValue, endValue)
}

func (u *UserCondition) PhoneNotBetween(startValue, endValue string) *UserCondition {
	return u.Where("phone not between ? and ?", startValue, endValue)
}

func (u *UserCondition) PhoneIn(inValues []string) *UserCondition {
	return u.Where("phone in (?)", inValues)
}

func (u *UserCondition) PhoneNotIn(inValues []string) *UserCondition {
	return u.Where("phone not in (?)", inValues)
}

func (u *UserCondition) GenderIsNull() *UserCondition {
	return u.Where("gender is null")
}

func (u *UserCondition) GenderIsNotNull() *UserCondition {
	return u.Where("gender is not null")
}

func (u *UserCondition) GenderEqualTo(value int32) *UserCondition {
	return u.Where("gender = ?", value)
}

func (u *UserCondition) GenderNotEqualTo(value int32) *UserCondition {
	return u.Where("gender <> ?", value)
}

func (u *UserCondition) GenderGreaterThan(value int32) *UserCondition {
	return u.Where("gender > ?", value)
}

func (u *UserCondition) GenderGreaterThanOrEqualTo(value int32) *UserCondition {
	return u.Where("gender >= ?", value)
}

func (u *UserCondition) GenderLessThan(value int32) *UserCondition {
	return u.Where("gender < ?", value)
}

func (u *UserCondition) GenderLessThanOrEqualTo(value int32) *UserCondition {
	return u.Where("gender <= ?", value)
}

func (u *UserCondition) GenderBetween(startValue, endValue int32) *UserCondition {
	return u.Where("gender between ? and ?", startValue, endValue)
}

func (u *UserCondition) GenderNotBetween(startValue, endValue int32) *UserCondition {
	return u.Where("gender not between ? and ?", startValue, endValue)
}

func (u *UserCondition) GenderIn(inValues []int32) *UserCondition {
	return u.Where("gender in (?)", inValues)
}

func (u *UserCondition) GenderNotIn(inValues []int32) *UserCondition {
	return u.Where("gender not in (?)", inValues)
}

func (u *UserCondition) StatusIsNull() *UserCondition {
	return u.Where("status is null")
}

func (u *UserCondition) StatusIsNotNull() *UserCondition {
	return u.Where("status is not null")
}

func (u *UserCondition) StatusEqualTo(value int32) *UserCondition {
	return u.Where("status = ?", value)
}

func (u *UserCondition) StatusNotEqualTo(value int32) *UserCondition {
	return u.Where("status <> ?", value)
}

func (u *UserCondition) StatusGreaterThan(value int32) *UserCondition {
	return u.Where("status > ?", value)
}

func (u *UserCondition) StatusGreaterThanOrEqualTo(value int32) *UserCondition {
	return u.Where("status >= ?", value)
}

func (u *UserCondition) StatusLessThan(value int32) *UserCondition {
	return u.Where("status < ?", value)
}

func (u *UserCondition) StatusLessThanOrEqualTo(value int32) *UserCondition {
	return u.Where("status <= ?", value)
}

func (u *UserCondition) StatusBetween(startValue, endValue int32) *UserCondition {
	return u.Where("status between ? and ?", startValue, endValue)
}

func (u *UserCondition) StatusNotBetween(startValue, endValue int32) *UserCondition {
	return u.Where("status not between ? and ?", startValue, endValue)
}

func (u *UserCondition) StatusIn(inValues []int32) *UserCondition {
	return u.Where("status in (?)", inValues)
}

func (u *UserCondition) StatusNotIn(inValues []int32) *UserCondition {
	return u.Where("status not in (?)", inValues)
}

func (u *UserCondition) RegisterIPPrefixLike(value string) *UserCondition {
	return u.Where("register_ip like ?", value+"%")
}

func (u *UserCondition) RegisterIPIsLike(value string) *UserCondition {
	return u.Where("register_ip like ?", "%"+value+"%")
}

func (u *UserCondition) RegisterIPIsNull() *UserCondition {
	return u.Where("register_ip is null")
}

func (u *UserCondition) RegisterIPIsNotNull() *UserCondition {
	return u.Where("register_ip is not null")
}

func (u *UserCondition) RegisterIPEqualTo(value string) *UserCondition {
	return u.Where("register_ip = ?", value)
}

func (u *UserCondition) RegisterIPNotEqualTo(value string) *UserCondition {
	return u.Where("register_ip <> ?", value)
}

func (u *UserCondition) RegisterIPGreaterThan(value string) *UserCondition {
	return u.Where("register_ip > ?", value)
}

func (u *UserCondition) RegisterIPGreaterThanOrEqualTo(value string) *UserCondition {
	return u.Where("register_ip >= ?", value)
}

func (u *UserCondition) RegisterIPLessThan(value string) *UserCondition {
	return u.Where("register_ip < ?", value)
}

func (u *UserCondition) RegisterIPLessThanOrEqualTo(value string) *UserCondition {
	return u.Where("register_ip <= ?", value)
}

func (u *UserCondition) RegisterIPBetween(startValue, endValue string) *UserCondition {
	return u.Where("register_ip between ? and ?", startValue, endValue)
}

func (u *UserCondition) RegisterIPNotBetween(startValue, endValue string) *UserCondition {
	return u.Where("register_ip not between ? and ?", startValue, endValue)
}

func (u *UserCondition) RegisterIPIn(inValues []string) *UserCondition {
	return u.Where("register_ip in (?)", inValues)
}

func (u *UserCondition) RegisterIPNotIn(inValues []string) *UserCondition {
	return u.Where("register_ip not in (?)", inValues)
}

func (u *UserCondition) RegisterTimeIsNull() *UserCondition {
	return u.Where("register_time is null")
}

func (u *UserCondition) RegisterTimeIsNotNull() *UserCondition {
	return u.Where("register_time is not null")
}

func (u *UserCondition) RegisterTimeEqualTo(value time.Time) *UserCondition {
	return u.Where("register_time = ?", value)
}

func (u *UserCondition) RegisterTimeNotEqualTo(value time.Time) *UserCondition {
	return u.Where("register_time <> ?", value)
}

func (u *UserCondition) RegisterTimeGreaterThan(value time.Time) *UserCondition {
	return u.Where("register_time > ?", value)
}

func (u *UserCondition) RegisterTimeGreaterThanOrEqualTo(value time.Time) *UserCondition {
	return u.Where("register_time >= ?", value)
}

func (u *UserCondition) RegisterTimeLessThan(value time.Time) *UserCondition {
	return u.Where("register_time < ?", value)
}

func (u *UserCondition) RegisterTimeLessThanOrEqualTo(value time.Time) *UserCondition {
	return u.Where("register_time <= ?", value)
}

func (u *UserCondition) RegisterTimeBetween(startValue, endValue time.Time) *UserCondition {
	return u.Where("register_time between ? and ?", startValue, endValue)
}

func (u *UserCondition) RegisterTimeNotBetween(startValue, endValue time.Time) *UserCondition {
	return u.Where("register_time not between ? and ?", startValue, endValue)
}

func (u *UserCondition) RegisterTimeIn(inValues []time.Time) *UserCondition {
	return u.Where("register_time in (?)", inValues)
}

func (u *UserCondition) RegisterTimeNotIn(inValues []time.Time) *UserCondition {
	return u.Where("register_time not in (?)", inValues)
}

func (u *UserCondition) LastLoginIPPrefixLike(value string) *UserCondition {
	return u.Where("last_login_ip like ?", value+"%")
}

func (u *UserCondition) LastLoginIPIsLike(value string) *UserCondition {
	return u.Where("last_login_ip like ?", "%"+value+"%")
}

func (u *UserCondition) LastLoginIPIsNull() *UserCondition {
	return u.Where("last_login_ip is null")
}

func (u *UserCondition) LastLoginIPIsNotNull() *UserCondition {
	return u.Where("last_login_ip is not null")
}

func (u *UserCondition) LastLoginIPEqualTo(value string) *UserCondition {
	return u.Where("last_login_ip = ?", value)
}

func (u *UserCondition) LastLoginIPNotEqualTo(value string) *UserCondition {
	return u.Where("last_login_ip <> ?", value)
}

func (u *UserCondition) LastLoginIPGreaterThan(value string) *UserCondition {
	return u.Where("last_login_ip > ?", value)
}

func (u *UserCondition) LastLoginIPGreaterThanOrEqualTo(value string) *UserCondition {
	return u.Where("last_login_ip >= ?", value)
}

func (u *UserCondition) LastLoginIPLessThan(value string) *UserCondition {
	return u.Where("last_login_ip < ?", value)
}

func (u *UserCondition) LastLoginIPLessThanOrEqualTo(value string) *UserCondition {
	return u.Where("last_login_ip <= ?", value)
}

func (u *UserCondition) LastLoginIPBetween(startValue, endValue string) *UserCondition {
	return u.Where("last_login_ip between ? and ?", startValue, endValue)
}

func (u *UserCondition) LastLoginIPNotBetween(startValue, endValue string) *UserCondition {
	return u.Where("last_login_ip not between ? and ?", startValue, endValue)
}

func (u *UserCondition) LastLoginIPIn(inValues []string) *UserCondition {
	return u.Where("last_login_ip in (?)", inValues)
}

func (u *UserCondition) LastLoginIPNotIn(inValues []string) *UserCondition {
	return u.Where("last_login_ip not in (?)", inValues)
}

func (u *UserCondition) LastLoginTimeIsNull() *UserCondition {
	return u.Where("last_login_time is null")
}

func (u *UserCondition) LastLoginTimeIsNotNull() *UserCondition {
	return u.Where("last_login_time is not null")
}

func (u *UserCondition) LastLoginTimeEqualTo(value time.Time) *UserCondition {
	return u.Where("last_login_time = ?", value)
}

func (u *UserCondition) LastLoginTimeNotEqualTo(value time.Time) *UserCondition {
	return u.Where("last_login_time <> ?", value)
}

func (u *UserCondition) LastLoginTimeGreaterThan(value time.Time) *UserCondition {
	return u.Where("last_login_time > ?", value)
}

func (u *UserCondition) LastLoginTimeGreaterThanOrEqualTo(value time.Time) *UserCondition {
	return u.Where("last_login_time >= ?", value)
}

func (u *UserCondition) LastLoginTimeLessThan(value time.Time) *UserCondition {
	return u.Where("last_login_time < ?", value)
}

func (u *UserCondition) LastLoginTimeLessThanOrEqualTo(value time.Time) *UserCondition {
	return u.Where("last_login_time <= ?", value)
}

func (u *UserCondition) LastLoginTimeBetween(startValue, endValue time.Time) *UserCondition {
	return u.Where("last_login_time between ? and ?", startValue, endValue)
}

func (u *UserCondition) LastLoginTimeNotBetween(startValue, endValue time.Time) *UserCondition {
	return u.Where("last_login_time not between ? and ?", startValue, endValue)
}

func (u *UserCondition) LastLoginTimeIn(inValues []time.Time) *UserCondition {
	return u.Where("last_login_time in (?)", inValues)
}

func (u *UserCondition) LastLoginTimeNotIn(inValues []time.Time) *UserCondition {
	return u.Where("last_login_time not in (?)", inValues)
}

func (u *UserCondition) CreateTimeIsNull() *UserCondition {
	return u.Where("create_time is null")
}

func (u *UserCondition) CreateTimeIsNotNull() *UserCondition {
	return u.Where("create_time is not null")
}

func (u *UserCondition) CreateTimeEqualTo(value time.Time) *UserCondition {
	return u.Where("create_time = ?", value)
}

func (u *UserCondition) CreateTimeNotEqualTo(value time.Time) *UserCondition {
	return u.Where("create_time <> ?", value)
}

func (u *UserCondition) CreateTimeGreaterThan(value time.Time) *UserCondition {
	return u.Where("create_time > ?", value)
}

func (u *UserCondition) CreateTimeGreaterThanOrEqualTo(value time.Time) *UserCondition {
	return u.Where("create_time >= ?", value)
}

func (u *UserCondition) CreateTimeLessThan(value time.Time) *UserCondition {
	return u.Where("create_time < ?", value)
}

func (u *UserCondition) CreateTimeLessThanOrEqualTo(value time.Time) *UserCondition {
	return u.Where("create_time <= ?", value)
}

func (u *UserCondition) CreateTimeBetween(startValue, endValue time.Time) *UserCondition {
	return u.Where("create_time between ? and ?", startValue, endValue)
}

func (u *UserCondition) CreateTimeNotBetween(startValue, endValue time.Time) *UserCondition {
	return u.Where("create_time not between ? and ?", startValue, endValue)
}

func (u *UserCondition) CreateTimeIn(inValues []time.Time) *UserCondition {
	return u.Where("create_time in (?)", inValues)
}

func (u *UserCondition) CreateTimeNotIn(inValues []time.Time) *UserCondition {
	return u.Where("create_time not in (?)", inValues)
}

func (u *UserCondition) UpdateTimeIsNull() *UserCondition {
	return u.Where("update_time is null")
}

func (u *UserCondition) UpdateTimeIsNotNull() *UserCondition {
	return u.Where("update_time is not null")
}

func (u *UserCondition) UpdateTimeEqualTo(value time.Time) *UserCondition {
	return u.Where("update_time = ?", value)
}

func (u *UserCondition) UpdateTimeNotEqualTo(value time.Time) *UserCondition {
	return u.Where("update_time <> ?", value)
}

func (u *UserCondition) UpdateTimeGreaterThan(value time.Time) *UserCondition {
	return u.Where("update_time > ?", value)
}

func (u *UserCondition) UpdateTimeGreaterThanOrEqualTo(value time.Time) *UserCondition {
	return u.Where("update_time >= ?", value)
}

func (u *UserCondition) UpdateTimeLessThan(value time.Time) *UserCondition {
	return u.Where("update_time < ?", value)
}

func (u *UserCondition) UpdateTimeLessThanOrEqualTo(value time.Time) *UserCondition {
	return u.Where("update_time <= ?", value)
}

func (u *UserCondition) UpdateTimeBetween(startValue, endValue time.Time) *UserCondition {
	return u.Where("update_time between ? and ?", startValue, endValue)
}

func (u *UserCondition) UpdateTimeNotBetween(startValue, endValue time.Time) *UserCondition {
	return u.Where("update_time not between ? and ?", startValue, endValue)
}

func (u *UserCondition) UpdateTimeIn(inValues []time.Time) *UserCondition {
	return u.Where("update_time in (?)", inValues)
}

func (u *UserCondition) UpdateTimeNotIn(inValues []time.Time) *UserCondition {
	return u.Where("update_time not in (?)", inValues)
}

func (u *UserCondition) Where(query any, args ...any) *UserCondition {
	switch obj := query.(type) {
	case string:
		if len(args) > 0 {
			u.StringCondition = append(u.StringCondition, obj)
			u.Condition.Args = append(u.Condition.Args, args...)
		} else {
			u.StringCondition = append(u.StringCondition, obj)
		}
	case map[string]any:
		if u.MapCondition == nil {
			u.MapCondition = obj
		} else {
			for key, val := range obj {
				u.MapCondition[key] = val
			}
		}
	}
	return u
}

func (u *UserCondition) OrderBy(orderByClause ...string) *UserCondition {
	u.OrderByClause = append(u.OrderByClause, orderByClause...)
	return u
}

func (u *UserCondition) GroupBy(groupByClause string) *UserCondition {
	u.GroupByClause = groupByClause
	return u
}

func (u *UserCondition) Having(query string, args ...any) *UserCondition {
	u.HavingCondition = query
	u.HavingArgs = args
	return u
}

func (u *UserCondition) Joins(query string, args ...any) *UserCondition {
	u.JoinCondition = append(u.JoinCondition, query)
	u.JoinArgs = append(u.JoinArgs, args...)
	return u
}

func (u *UserCondition) Build() *Condition {
	return &u.Condition
}
