// Code generated by MockGen. DO NOT EDIT.
// Source: server/service/health_check/interface.go
//
// Generated by this command:
//
//	mockgen -source=server/service/health_check/interface.go -destination=mocks/server/service/health_check/mock_interface.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	health_check "github.com/jasonlabz/generate-example-project/server/service/health_check"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockService) Check(ctx context.Context) (health_check.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(health_check.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockServiceMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockService)(nil).Check), ctx)
}

// CheckReadiness mocks base method.
func (m *MockService) CheckReadiness(ctx context.Context) (health_check.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckReadiness", ctx)
	ret0, _ := ret[0].(health_check.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckReadiness indicates an expected call of CheckReadiness.
func (mr *MockServiceMockRecorder) CheckReadiness(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckReadiness", reflect.TypeOf((*MockService)(nil).CheckReadiness), ctx)
}
