// Code generated by MockGen. DO NOT EDIT.
// Source: server/manager/health_check/interface.go
//
// Generated by this command:
//
//	mockgen -source=server/manager/health_check/interface.go -destination=mocks/server/manager/health_check/mock_interface.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockManager) Check(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockManagerMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockManager)(nil).Check), ctx)
}

// CheckReadiness mocks base method.
func (m *MockManager) CheckReadiness(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckReadiness", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckReadiness indicates an expected call of CheckReadiness.
func (mr *MockManagerMockRecorder) CheckReadiness(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckReadiness", reflect.TypeOf((*MockManager)(nil).CheckReadiness), ctx)
}

// MockHealthProbe is a mock of HealthProbe interface.
type MockHealthProbe struct {
	ctrl     *gomock.Controller
	recorder *MockHealthProbeMockRecorder
	isgomock struct{}
}

// MockHealthProbeMockRecorder is the mock recorder for MockHealthProbe.
type MockHealthProbeMockRecorder struct {
	mock *MockHealthProbe
}

// NewMockHealthProbe creates a new mock instance.
func NewMockHealthProbe(ctrl *gomock.Controller) *MockHealthProbe {
	mock := &MockHealthProbe{ctrl: ctrl}
	mock.recorder = &MockHealthProbeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthProbe) EXPECT() *MockHealthProbeMockRecorder {
	return m.recorder
}

// Probe mocks base method.
func (m *MockHealthProbe) Probe(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probe", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Probe indicates an expected call of Probe.
func (mr *MockHealthProbeMockRecorder) Probe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockHealthProbe)(nil).Probe), ctx)
}
