// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jasonlabz/generate-example-project/server/manager (interfaces: HealthCheckManager,HealthProbe)
//
// Generated by this command:
//
//	mockgen -destination=mock_manager.go -package=mocks github.com/jasonlabz/generate-example-project/server/manager HealthCheckManager,HealthProbe
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHealthCheckManager is a mock of HealthCheckManager interface.
type MockHealthCheckManager struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckManagerMockRecorder
	isgomock struct{}
}

// MockHealthCheckManagerMockRecorder is the mock recorder for MockHealthCheckManager.
type MockHealthCheckManagerMockRecorder struct {
	mock *MockHealthCheckManager
}

// NewMockHealthCheckManager creates a new mock instance.
func NewMockHealthCheckManager(ctrl *gomock.Controller) *MockHealthCheckManager {
	mock := &MockHealthCheckManager{ctrl: ctrl}
	mock.recorder = &MockHealthCheckManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthCheckManager) EXPECT() *MockHealthCheckManagerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthCheckManager) Check(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockHealthCheckManagerMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthCheckManager)(nil).Check), ctx)
}

// MockHealthProbe is a mock of HealthProbe interface.
type MockHealthProbe struct {
	ctrl     *gomock.Controller
	recorder *MockHealthProbeMockRecorder
	isgomock struct{}
}

// MockHealthProbeMockRecorder is the mock recorder for MockHealthProbe.
type MockHealthProbeMockRecorder struct {
	mock *MockHealthProbe
}

// NewMockHealthProbe creates a new mock instance.
func NewMockHealthProbe(ctrl *gomock.Controller) *MockHealthProbe {
	mock := &MockHealthProbe{ctrl: ctrl}
	mock.recorder = &MockHealthProbeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthProbe) EXPECT() *MockHealthProbeMockRecorder {
	return m.recorder
}

// Probe mocks base method.
func (m *MockHealthProbe) Probe(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probe", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Probe indicates an expected call of Probe.
func (mr *MockHealthProbeMockRecorder) Probe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockHealthProbe)(nil).Probe), ctx)
}
