// Code generated by MockGen. DO NOT EDIT.
// Source: F:/baidu/aiib-go/generate-example-project/server/service/health_check/interface.go
//
// Generated by this command:
//
//	mockgen -source F:/baidu/aiib-go/generate-example-project/server/service/health_check/interface.go -destination F:/baidu/aiib-go/generate-example-project/server/mocks/server/service/health_check/mock_interface.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	health_check "github.com/jasonlabz/generate-example-project/server/service/health_check"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthCheckService is a mock of HealthCheckService interface.
type MockHealthCheckService struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckServiceMockRecorder
	isgomock struct{}
}

// MockHealthCheckServiceMockRecorder is the mock recorder for MockHealthCheckService.
type MockHealthCheckServiceMockRecorder struct {
	mock *MockHealthCheckService
}

// NewMockHealthCheckService creates a new mock instance.
func NewMockHealthCheckService(ctrl *gomock.Controller) *MockHealthCheckService {
	mock := &MockHealthCheckService{ctrl: ctrl}
	mock.recorder = &MockHealthCheckServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthCheckService) EXPECT() *MockHealthCheckServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthCheckService) Check(ctx context.Context) (health_check.HealthCheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(health_check.HealthCheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockHealthCheckServiceMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthCheckService)(nil).Check), ctx)
}
